# Generated by Django 4.1.2 on 2022-12-26 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("knowledgebase", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="gdocauthor",
            unique_together={("gdoc", "author")},
        ),
    ]
