# Generated by Django 4.1.2 on 2022-12-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledgebase", "0002_alter_gdocauthor_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="gdoc",
            name="practiceAreas",
            field=models.ManyToManyField(blank=True, to="knowledgebase.practicearea"),
        ),
    ]
