# Generated by Django 4.1.2 on 2022-12-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledgebase", "0003_practicearea_gdoc_practiceareas"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="gdoc",
            name="technologies",
            field=models.ManyToManyField(blank=True, to="knowledgebase.technology"),
        ),
        migrations.AddField(
            model_name="gdoc",
            name="tools",
            field=models.ManyToManyField(blank=True, to="knowledgebase.tool"),
        ),
    ]
