FROM hfla-django
# RUN mkdir -p /node/node_modules && chown -R node:node /node

# add bash


# Create app directory
WORKDIR /

COPY ./django-root/requirements.txt ./
COPY ./django-root ./
CMD ["python", "manage.py", "runserver"]
EXPOSE 8000