#!/bin/bash
export DATABASE_HOST=db
export DATABASE_PORT=5434
export DJANGO_SUPERUSER=admin
export DJANGO_SUPERUSER_EMAIL=$DJANGO_SUPERUSER@fake.com
export DJANGO_SUPERUSER_PASSWORD=$DJANGO_SUPERUSER
source ./start.sh 8001