# Generated by Django 4.2.7 on 2024-02-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people_depot", "0003_remove_organization_uuid_organization_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="practicearea",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
