# Generated by Django 4.2.7 on 2024-04-14 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_populate_asset_type'),
        ('data', '0007_phase_seed'),
    ]

    operations = [
    ]
