# Generated by Django 4.2.7 on 2023-12-23 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("people_depot", "0001_initial"),
        ("kb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetgroupuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="assetgroup",
            name="phase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="kb.phase"
            ),
        ),
        migrations.AddField(
            model_name="assetgroup",
            name="practiceAreas",
            field=models.ManyToManyField(blank=True, to="people_depot.practicearea"),
        ),
        migrations.AddField(
            model_name="assetgroup",
            name="tools",
            field=models.ManyToManyField(blank=True, to="people_depot.tool"),
        ),
        migrations.AlterUniqueTogether(
            name="assetgroupuser",
            unique_together={("assetGroup", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="assetgroup",
            unique_together={("slug", "phase")},
        ),
    ]
