# Generated by Django 4.2.7 on 2023-12-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kb", "0002_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
    ]
