# Generated by Django 4.2.7 on 2024-01-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people_depot", "0001_initial"),
        ("kb", "0002_step2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assetgroup",
            name="tools",
        ),
        migrations.AddField(
            model_name="asset",
            name="tools",
            field=models.ManyToManyField(blank=True, to="people_depot.tool"),
        ),
    ]
