# Generated by Django 4.2.7 on 2023-12-27 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kb", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PracticeArea",
        ),
    ]
