# Generated by Django 4.2.7 on 2024-01-15 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("kb", "0003_remove_assetgroup_tools_asset_tools"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="assetGroup",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="kb.assetgroup",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="asset",
            name="asset_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="kb.assettype",
            ),
            preserve_default=False,
        ),
    ]
