# Generated by Django 4.2.7 on 2024-01-14 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kb", "0003_assettype"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PracticeArea",
        ),
    ]
