# Generated by Django 4.2.7 on 2024-01-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kb", "0004_asset_assetgroup_asset_asset_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assetgroup",
            old_name="title",
            new_name="name",
        ),
    ]
