# Generated by Django 4.2.7 on 2024-01-24 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people_depot", "0001_initial"),
        ("kb", "0005_rename_title_assetgroup_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asset",
            old_name="assetGroup",
            new_name="asset_group",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="tools",
        ),
        migrations.RemoveField(
            model_name="assetgroup",
            name="practiceAreas",
        ),
        migrations.CreateModel(
            name="AssetTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kb.asset"
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people_depot.tool",
                    ),
                ),
            ],
            options={
                "unique_together": {("asset", "tool")},
            },
        ),
        migrations.CreateModel(
            name="AssetPracticeArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kb.asset"
                    ),
                ),
                (
                    "practice_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people_depot.practicearea",
                    ),
                ),
            ],
            options={
                "unique_together": {("asset", "practice_area")},
            },
        ),
        migrations.CreateModel(
            name="AssetGroupTopicArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "asset_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kb.asset"
                    ),
                ),
                (
                    "topic_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kb.topicarea"
                    ),
                ),
            ],
            options={
                "unique_together": {("asset_group", "topic_area")},
            },
        ),
    ]
