# Generated by Django 4.2.7 on 2024-01-27 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kb", "0008_assetcategory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assetcategory",
            options={"ordering": ["name"], "verbose_name_plural": "asset categories"},
        ),
        migrations.AddField(
            model_name="assettype",
            name="asset_category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="kb.assetcategory",
            ),
            preserve_default=False,
        ),
    ]
