# Generated by Django 4.2.7 on 2024-01-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kb", "0009_alter_assetcategory_options_assettype_asset_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assetgroup",
            options={"ordering": ["name", "group_version"]},
        ),
        migrations.AlterUniqueTogether(
            name="asset",
            unique_together={("asset_group", "title", "phase")},
        ),
        migrations.AddField(
            model_name="assetgroup",
            name="group_version",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="assetgroup",
            name="name",
            field=models.CharField(default="", max_length=70, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="assetgroup",
            unique_together={("name", "group_version")},
        ),
    ]
