# Generated by Django 4.2.7 on 2024-01-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kb", "0010_alter_assetgroup_options_alter_asset_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="google_id",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="assetgroup",
            name="name",
            field=models.CharField(default="", max_length=70),
        ),
    ]
