# Generated by Django 4.2.7 on 2024-01-30 18:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("people_depot", "0001_initial"),
        ("kb", "0011_alter_asset_google_id_alter_assetgroup_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AssetGroupTopicArea",
            new_name="AssetGroupTopicAreas",
        ),
        migrations.RenameModel(
            old_name="AssetPracticeArea",
            new_name="AssetPracticeAreas",
        ),
        migrations.RenameModel(
            old_name="AssetTool",
            new_name="AssetTools",
        ),
        migrations.RenameModel(
            old_name="AssetUser",
            new_name="AssetUsers",
        ),
    ]
