# Generated by Django 4.2.7 on 2024-02-21 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people_depot", "0005_alter_organization_options"),
        ("kb", "0012_rename_assetgrouptopicarea_assetgrouptopicareas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="people_depot.organization",
            ),
            preserve_default=False,
        ),
    ]
