# Generated by Django 4.2.7 on 2024-02-21 19:56

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("kb", "0013_asset_organization"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assettype",
            options={
                "ordering": [
                    "asset_category__name",
                    django.db.models.functions.text.Upper("name"),
                ]
            },
        ),
    ]
