# Generated by Django 4.1.2 on 2023-11-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_kb_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="programarea",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="programarea",
            name="image",
            field=models.URLField(blank=True),
        ),
    ]
