# Generated by Django 4.1.2 on 2023-12-13 00:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_kb_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicArea',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=70, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
